# Generated by Django 2.1.7 on 2019-04-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
